Add `delete-old-binning-data` command to re_id_tool.py
microbiomedata/nmdc_automation pull request #69
Opened 2024-03-11 18:03 UTC by mbthornton-lbl

This PR adds a new Click command to `re_id_tool.py` called **delete-old-binning-data**

    Delete old binning data from the MongoDB database.
    
    Some binning data objects can be found by their data_object_type: 'Metagenome Bins' or 'CheckM Statistics'
    Un-typed data objects can be found by looking for 'metabat2' in the description
    
    If the --no-delete flag is set, the script will not delete any records, but will log the records that would be
    deleted.

2024-03-11 18:16 UTC, mbthornton-lbl commented
[delete.log](https://github.com/microbiomedata/nmdc_automation/files/14562947/delete.log)

2024-03-11 19:05 UTC, aclum requested changes
The 'emsl' data objects are a mix of orphaned, lipidomics, and one proteomics record. some of them are mentioned by the omics records so we can't just bulk delete them. If we are sure the records are orphaned & that all studies have referential integrity we can delete them.

2024-03-11 23:42 UTC, aclum approved these changes

2024-03-12 17:09 UTC, mbthornton-lbl commented
@aclum I have updated this command to delete:
- Binning data objects with non-compliant IDs
- Lipidomics omics processing records and data objects
[delete_old_binn_and_lipidomics.log](https://github.com/microbiomedata/nmdc_automation/files/14576215/delete_old_binn_and_lipidomics.log)

2024-03-12 17:15 UTC, merged